obj-$(CONFIG_USB_CANINOS) += caninoshcd.o
caninoshcd-y := caninos-core.o caninos-hcd.o caninos-ring.o \
caninos-td.o caninos-ctrl.o caninos-intr.o caninos-xfer.o \
caninos-ep.o caninos-pool.o caninos-hotplug.o

