# SPDX-License-Identifier: GPL-2.0+
dtb-$(CONFIG_ARCH_CANINOS) += caninos-k7.dtb \
							  caninos-k7-nostdout.dtb \
							  caninos-k7-lora.dtb \
							  caninos-k7-lora-p2p.dtb \
							  caninos-k7-gigabit.dtb \
							  caninos-k7-base31-megabit.dtb \
							  caninos-k7-base31-gigabit.dtb \
							  caninos-k7-base31-gigabit-lora-p2p.dtb
