# SPDX-License-Identifier: GPL-2.0+
dtb-$(CONFIG_ARCH_CANINOS) += \
	k7-bankhar10.dtb \
	k7-base10a.dtb \
	k7-base10a-silent.dtb \
	k7-base21.dtb \
	k7-base21-silent.dtb \
	k7-base22.dtb \
	k7-base22-silent.dtb \
	k7-base31-giga.dtb \
	k7-base31-giga-silent.dtb \
	k7-base31-mega.dtb \
	k7-base31-mega-silent.dtb \
	k7-omni10.dtb \
	k7-omni10-silent.dtb
