# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_MFD_CANINOS_PMIC) += pmic-core.o pmic-i2c.o
obj-$(CONFIG_MFD_CANINOS_AUXADC) += pmic-auxadc.o
obj-$(CONFIG_MFD_CANINOS_BATTERY) += pmic-battery.o
obj-$(CONFIG_MFD_CANINOS_GPIO) += pmic-gpio.o
